export const SET_ORDEM_SERVICO = 'ORDEM_SERVICO/SET_ORDEM_SERVICO';
export const SET_ORDEM_SERVICOS = 'ORDEM_SERVICO/SET_ORDEM_SERVICOS';
export const SET_ORDEM_SERVICO_STATUS = 'ORDEM_SERVICO/SET_ORDEM_SERVICO_STATUS';
export const SET_ORDEM_SERVICO_EVOLUCOES = 'ORDEM_SERVICO/SET_ORDEM_SERVICO_EVOLUCOES';
export const SET_ORDEM_SERVICO_EVOLUCOES_DIRECT = 'ORDEM_SERVICO/SET_ORDEM_SERVICO_EVOLUCOES_DIRECT';
export const SET_ORDEM_SERVICO_EVOLUCAO = 'ORDEM_SERVICO/SET_ORDEM_SERVICO_EVOLUCAO';

